export const courseSections = [
  {
    subject: "IT-WST01",
    year: "2023-2024 2nd sem",
    teacher: "Rose Anne G. Cochanco",
    section: "1E",
    laboratoriesLink: "/itwst01",
    caseStudyLink: "https://webwisee.vercel.app/",
  },
  {
    subject: "IT-WST02",
    year: "2024-2025 1st sem",
    teacher: "Rose Anne G. Cochanco",
    section: "2A",
    laboratoriesLink: "/itwst02",
    caseStudyLink: "https://rnlsevilla.vercel.app/",
  },
  {
    subject: "IT-PF01",
    year: "2024-2025 1st sem",
    teacher: "Prince Mert Nicolas",
    section: "2A",
    laboratoriesLink: "/itpf01",
  },
  {
    subject: "IT-PF02",
    year: "2024-2025 2nd sem",
    teacher: "Prince Mert Nicolas",
    section: "2A",
    laboratoriesLink: "/itpf02",
  },
  {
    subject: "IT-HCI01",
    year: "2024-2025 2nd sem",
    teacher: "Marcelino Collado Jr.",
    section: "2A",
    laboratoriesLink: "/ithci01",
  },
  {
    subject: "CC-104",
    year: "2024-2025 2nd sem",
    teacher: "Apple Oliveros",
    section: "2A",
    laboratoriesLink: "/cc104",
  },
  {
    subject: "CC-105",
    year: "2024-2025 2nd sem",
    teacher: "Cris Norman Olipas",
    section: "2A",
    laboratoriesLink: "/cc105",
  },
  {
    subject: "IT-IPT01",
    year: "2025-2026 1st sem",
    teacher: "Melgine Bauat",
    section: "3C",
    laboratoriesLink: "/itipt01",
  },
  {
    subject: "IT-IPT02",
    year: "2025-2026 1st sem",
    teacher: "Nino Herrera",
    section: "3C",
    laboratoriesLink: "/itipt02",
  },
  {
    subject: "IT-WST03",
    year: "2025-2026 2nd sem",
    teacher: "Andrew Ceasar A. Villegas",
    section: "3C",
    laboratoriesLink: "/itwst03",
  },
  {
    subject: "IT-WST05",
    year: "2025-2026 2nd sem",
    teacher: "Angelito I. Cunanan Jr.",
    section: "3C",
    laboratoriesLink: "/itwst05",
  },
];
